test_server_api:
    image: "python:3.5"
    before_script:
        - cd server
        - pip install virtualenv
        - virtualenv venv
        - venv/bin/pip install -r requirements.txt
        - venv/bin/python --version
    script:
        - "venv/bin/coverage run -p server.py &"
        - "venv/bin/pytest tests"
        - "jobid=$(jobs|awk '{print $1}'| sed 's/[^0-9]*//g')"
        - "jobpid=$(jobs -p)"
        - "sleep 5s && kill -s 2 $jobpid"
        - "fg $jobid"
        - "jobs"
        - venv/bin/coverage combine
        - venv/bin/coverage report  --include="./*"
    stage: test
    coverage: '/TOTAL\s*\d+\s*\d+\s*(\d+)\%$/'
