image: "python:3.5"
before_script:
    - python --version
    - pip install virtualenv
    - virtualenv -p python venv
    - venv/bin/pip install -r requirements.txt
    - venv/bin/python --version
testinglocal:
    script:
        - "cd server && ../venv/bin/python server.py &"
        - "cd server && ../venv/bin/pytest test_.py"
