test_server_api:
    only:
        - tags
    except:
        - branches
    image: "python:3.5"
    before_script:
        - cd server
        - pip install virtualenv
        - virtualenv venv
        - venv/bin/pip install -r requirements.txt
        - venv/bin/python --version
    script:
        - "venv/bin/python server.py &"
        - "venv/bin/py.test --cov=tests"
    stage: test
    coverage: '/TOTAL\s*\d+\s*\d+\s*(\d+)\%$/'
    after_script:
        - kill %-
