test_server_ram_db:
    image: "python:3.5"
    before_script:
        - cd server
        - pip install pipenv
        - pipenv install --ignore-pipfile --dev
    script:
        - "printf '\n\n' | pipenv run -p server.py &"
        - "sleep 10s && pipenv run dummy_setup.py"
        - "sleep 10s && pipenv run pytest tests"
    stage: test
test_server_mongo:
    image: "python:3.5"
    variables:
        MONGO_URI: "mongodb://mongo/exchange"
        USE_MONGO: "1"
    services:
        - mongo
    before_script:
        - cd server
        - pip install pipenv
        - pipenv install --ignore-pipfile --dev
    script:
        - "printf '\n\n' | pipenv run server.py &"
        - "sleep 10s && pipenv run dummy_setup.py"
        - "sleep 10s && pipenv run pytest tests"
    stage: test
