before_script:
    - "virtualenv -p python3 venv"
    - "venv/bin/pip install -r requirements.txt"
after_script:
    - "rm -rf venv"
testinglocal:
    script:
        - "venv/bin/python server/server.py &"
        - "venv/bin/pytest server/test_.py"
    only:
        - master
