before_script:
    - apt-get install -y python3-dev python3-pip
    - pip3 install -r requirements.txt
testinglocal:
    script:
        - "python3 server/server.py &"
        - pytest server/test_.py
