image: "python:3.5"
before_script:
    - python --version
    - pip install virtualenv
    - virtualenv -p python venv
    - venv/bin/pip install -r requirements.txt
testinglocal:
    script:
        - "venv/bin/python server/server.py &"
        - venv/bin/pytest server/test_.py
