test_server_api:
    image: "python:3.5"
    before_script:
        - cd server
        - pip install pipenv
        - pipenv install --ignore-pipfile --dev
    script:
        - "printf '\n\n' | pipenv run -p server.py &"
        - "sleep 10s && pipenv run dummy_setup.py"
        - "sleep 10s && pipenv run pytest tests"
    stage: test
